---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sonarr-anime
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  path: ./kubernetes/apps/media/sonarr-anime/app
  dependsOn:
    - name: onepassword
      namespace: external-secrets
    - name: crunchy-pgo-clusters
      namespace: database
    - name: vpn-gateway
      namespace: network
    - name: media-shared
      namespace: media
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 10Gi
