# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:vAek91suc0A8duUnDeYukzlY7JzS352h83ynAZDpZSVtOVe3,iv:n4yg0AkBPupfjQRr8QIAGNFzxsw15RHBM9duuEKYWRk=,tag:3T4Zf3Fx5MuvXj846UJjTQ==,type:str]
  credentials.json: ENC[AES256_GCM,data:EP8g5cdwMvkylOSV9iCx47PD5n4Q9A2Ot1XQ54AaF1P3WwpxM2r0vp6fJV4C4SIzct4omkQFH+uvXJqJG2FO3PPDa2ze/eogpRq4/RVaZCOZsI62RD2rO0kqHEpsGVwR06qgmFaY6uGxEClM5AU/EuSIu+/w/EOf6yOnGuFVAOfPv4jQkX5/H2BMfAJ8DWxSOdz96HOo+G13gbBAxnD44aPMO1LPSedQOwAoLQVLLw==,iv:rBsB2ulzlcKMOxBwOG24rB5sGk2LQYxiizcBnfpx6Uk=,tag:zhnmPWKGwUmgcU8VZqz6dw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1pscs26yljjxv8f4z5x8pdhxv03cllnxs4kjj4k3zlacynd6axg9qa5jcar
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZ3h3akdMc2t3azV3b3Zt
        L3gwMnhwS0FWVXlxem9Pc3ViMW11eXVuTWlZCjNIT21IWEEzV1FYMko1OFN1Ulhi
        aDR4bDR4UTFHZTVZNXo1d3EzS1NXalEKLS0tIFhVYmNlenFQNVNaV0h0OXh6Z1BF
        bzY4ZkJ3S284VkJxU2xNU1VOVzdUcWsKK4JfcxpYaMCBpu3+AlfR8HjIF+1C7dSX
        sSJLBmgJb4yfWf+Dge6N6oUwh+W0QdQ6cWSnyrUDcNsGD1kVNeb/tQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-08T18:06:25Z"
  mac: ENC[AES256_GCM,data:mS6fJcuwET3zdxHTCt1FaxARPlHNJbwC2hJadmyLgpk2D6dUSMcfp5GYToFSXMqQPGGdN7wlECLyQNBRPc/kvEWcVsZcI2UNOw+isZe/ONArwarO1pS9Doe2WfgFx8pm58S243bvH5uashdwvR7Kvjb+/qYyYOqc9tc5Cc+EzFY=,iv:mUQjekCajexziYI/UpyhYn/DsLGu6mRHFU22WhtBRws=,tag:kzBmofWkbGJAff0Y8dnpkA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
