---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age10umqlxh72ven7hfqr2k39fssfktjhdzc87zpqqn8nv2yzjqhcg0qz2l6xv"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age10umqlxh72ven7hfqr2k39fssfktjhdzc87zpqqn8nv2yzjqhcg0qz2l6xv"
stores:
  yaml:
    indent: 2
