# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:7weutXx7/7OW/HtdlI46KViFTYuE/weUIrIIEajyoA8=,iv:4N+PPuoXVbIrO1uHJYWqwS0gqMPoK0wOZCWq1ZNY3xM=,tag:fjkcwWM3500vhetyeXnf4Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1pscs26yljjxv8f4z5x8pdhxv03cllnxs4kjj4k3zlacynd6axg9qa5jcar
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeWdkb1VIcmpnT0VQZHVU
        cHk0WWNzOVR2M2Q2c1Y1MmYzZnJlQjlva2g4CjJsU3dMOE9GR3hhRzVSK21ZWVNl
        bTk5WVBYZDFyWnkrWGI2Tm5XR2VzUk0KLS0tIFcxQjhrenNUNFNGbVpMTUk2ckVj
        L2lWeTdNKzhHVmFGUURkZHZuSXNCOFkKi3zmIrTj7+DgJb0vgSbYdmlwqM+5eKWd
        OjIF1fgJ6LOalKox1lfkUhvlH0bKTpwGbS5H4j4/8CcjyHsex3N7mw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-08T18:06:25Z"
  mac: ENC[AES256_GCM,data:ooGPxezp64PdHXjoarVwJjKmLCL2+rC71y0tt8Rp3x/Ocq3Q0JXDnM26kH0ojWR4hJj35dnRQfc7SvGXAI8316YUhtS06dpS4SFCbTsg87pNqCX/vNLHxN+AmsrEvc+qk1p5XqeVy1e3YO9g1hAqvJMbF5sDr9dmAwhSreV0bRY=,iv:RcK5fmqDXoBf3mcxilAFWAsEUW81VM036kqQKr9zYeA=,tag:KjVD8KJBEjiR3UKDSmZ5Qw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
