---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app hoarder-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *app
    template:
      data:
        # App
        BROWSER_WEB_URL: http://hoarder-chrome.default.svc.cluster.local:9222
        CRAWLER_DOWNLOAD_BANNER_IMAGE: "true"
        CRAWLER_ENABLE_ADBLOCKER: "true"
        CRAWLER_STORE_SCREENSHOT: "true"
        DATA_DIR: /data
        # DISABLE_SIGNUPS: "true"
        MEILI_ADDR: http://hoarder-meilisearch.default.svc.cluster.local:7700
        NEXTAUTH_SECRET: "{{ .HOARDER_ENCRYPTION_KEY }}"
        MEILI_MASTER_KEY: "{{ .HOARDER_MEILISEARCH_MASTER_KEY }}"
        DISABLE_PASSWORD_AUTH: "true"
        DISABLE_NEW_RELEASE_CHECK: "true"
        OPENAI_API_KEY: "{{ .HOARDER_OPENAI_KEY }}"
        # MeiliSearch
        MEILI_NO_ANALYTICS: "true"
        # OAuth
        NEXTAUTH_URL: "https://hoarder.nimbus.casa"
        OAUTH_CLIENT_ID: "{{ .HOARDER_OAUTH_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .HOARDER_OAUTH_CLIENT_SECRET }}"
        OAUTH_WELLKNOWN_URL: "{{ .HOARDER_OAUTH_WELLKNOWN_URL }}"
        OAUTH_PROVIDER_NAME: "Nimbus SSO"

        OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: "true"

  dataFrom:
    - extract:
        key: hoarder
