---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: jellyfin
  values:
    controllers:
      main:
        replicas: 1
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/jellyfin/jellyfin
              tag: 10.10.7
            env:
              TZ: America/New_York
              JELLYFIN_PublishedServerUrl: "https://jellyfin.${SECRET_DOMAIN}"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8096
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 6
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 4Gi
        pod:
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
            fsGroup: 1001
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [44, 107]
            seccompProfile: { type: RuntimeDefault }
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: jellyfin
    service:
      main:
        controller: main
        ports:
          http:
            port: *port
    route:
      main:
        hostnames: ["jellyfin.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: jellyfin
                port: *port
    persistence:
      config:
        existingClaim: jellyfin
        globalMounts:
          - path: /config
      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
      transcodes:
        type: emptyDir
        globalMounts:
          - path: /cache/transcodes
      media:
        existingClaim: mediastore-nfs-pvc
        globalMounts:
          - path: /mediastore
