---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      main:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.0
            env:
              TZ: America/New_York
              QBT_WEBUI_PORT: &port 8080
              QBITTORRENT__BT_PORT: &torrentPort 50413
              QBT_Application__MemoryWorkingSetLimit: 6000
              QBT_Preferences__WebUI__AlternativeUIEnabled: false
              QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: true
              QBT_Preferences__WebUI__AuthSubnetWhitelist: |-
                10.0.0.0/8, 192.168.0.0/16
              QBT_Preferences__WebUI__LocalHostAuth: false
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
              runAsUser: 1001
              runAsGroup: 1001
              runAsNonRoot: true
            resources:
              requests:
                cpu: 150m
                memory: 2Gi
              limits:
                memory: 8Gi
        pod:
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
            supplementalGroups: [10000]
            seccompProfile: { type: RuntimeDefault }
          annotations:
            setGateway: "true"
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: qbittorrent
    service:
      main:
        controller: main
        ports:
          http:
            port: *port
          bittorrent:
            enabled: true
            port: *torrentPort
            protocol: TCP
    route:
      main:
        hostnames: ["qb.nimbus.casa"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: qbittorrent
                port: *port
    persistence:
      config:
        existingClaim: qbittorrent
      tmp:
        type: emptyDir
      media:
        enabled: true
        existingClaim: mediastore-nfs-pvc
        globalMounts:
          - path: /mediastore
