[core]
toplevel = /opt/nexus/lore
log = ${toplevel}/grokmirror.log

[remote]
site = https://lore.kernel.org
manifest = https://lore.kernel.org/manifest.js.gz

[pull]
include = /bpf/*
          /damon/*
          /kvm/*
          /linux-mm/*
          /lkml/*
          /llvm/*
          /netdev/*
          /rust-for-linux/*
          /sched-ext/*
          /stable/*
pull_threads = 2
