---
system_hostname: nexus-kb
system_fqdn: nexus-kb.kbcb.tansanrao.net
system_timezone: UTC

ssh_listen_port: 22

common_extra_apt_packages:
  - git
  - openssl
  - grokmirror
  - qemu-guest-agent
common_extra_services:
  - qemu-guest-agent

# Shared admin authentication and Git mailing-list removal release.
nexus_revision: fe493fb8ca7633c2e9c1a4be3e87904dddd63b55
