---
system_hostname: nexus-kb
system_fqdn: nexus-kb.kbcb.tansanrao.net
system_timezone: UTC

ssh_listen_port: 22

common_extra_apt_packages:
  - git
  - openssl
  - grokmirror
  - qemu-guest-agent
common_extra_services:
  - qemu-guest-agent

# Shared admin authentication and Git mailing-list removal release.
nexus_revision: 4afab0aebdec4a9527d61db915bd695d09b95ba4
