---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./controlplaneio.yaml
  - ./coredns.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./metrics-server.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./external-secrets.yaml
  - ./piraeus.yaml
  - ./backube.yaml
  - ./rook-ceph.yaml
  - ./tailscale-charts.yaml
  - ./crunchydata.yaml
  - ./authentik-charts.yaml
  - ./csi-driver-smb.yaml
  - ./cloudnative-pg.yaml
