---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hoarder
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      hoarder:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/hoarder-app/hoarder
              tag: latest@sha256:e0682981becfcd65e4e56ebfebf8e3186334de7356710628513942e8d331c2aa
            envFrom: &env
              - secretRef:
                  name: hoarder-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

      chrome:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: gcr.io/zenika-hub/alpine-chrome
              tag: 124
            command:
              - chromium-browser
            args:
              - --headless
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=9222
              - --hide-scrollbars
            securityContext:
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

      meilisearch:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - hoarder
                  topologyKey: kubernetes.io/hostname
        containers:
          app:
            image:
              repository: docker.io/getmeili/meilisearch
              tag: v1.12.8
            envFrom: *env
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

    service:
      app:
        controller: hoarder
        ports:
          http:
            port: 3000
      chrome:
        controller: chrome
        ports:
          http:
            port: 9222
      meilisearch:
        controller: meilisearch
        ports:
          http:
            port: 7700

    ingress:
      app:
        className: "external"
        annotations:
          external-dns.alpha.kubernetes.io/target: external.nimbus.casa
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: hoarder.nimbus.casa
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        existingClaim: hoarder
        advancedMounts:
          hoarder:
            app:
              - path: /data
                subPath: hoarder
          meilisearch:
            app:
              - path: /meili_data
                subPath: meilisearch
