apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:l2sjyEpFxrWKBb0=,iv:9Ga7cRN2hE4TFpiTVV04zw4+mwZGErrbwoWL0JpVsVY=,tag:+Km+l7eAI9OMhKKzO6ey9g==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:vT1Za2DXrqJWeHee++htnCscZ5t/rmQAD/NfG9Y2Xy7pk0sU,iv:IThg7jUFfYF0L0rkOFatiPiCY41KAtqGG7evBVRthr4=,tag:MC35ouULXDbKbBi+f5Gc/w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1pscs26yljjxv8f4z5x8pdhxv03cllnxs4kjj4k3zlacynd6axg9qa5jcar
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVjQ3bEFOVHlhOUxGMTVD
        ZWFMaEpXc2FyUXBQR3dTNEo5dW5lZnFCbVNRCjVFNU9tVDFkc0xOSGp6bnFaOFJs
        UVQ1dnhGN1FnN1d6ZjE4WnNRdVVTdncKLS0tIHl0N1VKcmFwZ3c4OUp2R3FnNWhY
        U0hGbWxXaHJWSlVJQXVLc21zYytXUTQK8mNrIz/vC8uNwSlN63ssMJdcKt3rFaX5
        f/ibL5zIRXDZGvZRKZoKl8UajXdkc92vqTHEafh/F3JYSc3SgFWi1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-08T18:41:51Z"
  mac: ENC[AES256_GCM,data:2Azm9t3wRvH0bGHNng2aQawUogdRefe6xHz39RWxgToHPqIyhvlM/fxABMLKspfW4q6OXafggTsM6MUfmBW3KxGKgIUXNm7INepeegXRAbwhoihXPECazrCxIw9U0qBGdWiwxZGxmek3sqjgln4UBaUamv+L23MlZ6WDEHWlv3E=,iv:RLSGrzPsb36GA7ySlmM0+pwz60KbjYeLP2+2XDaU3Pk=,tag:rsUJfgGGbrxQiVC2BCq9gA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
