apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:/OCiyuT8tOu6+JE=,iv:cTToTtThSPkbM3StGtAeR6uJuuzh9TTWLwqP6vuAMWo=,tag:1wVAxfoyFkw0LKAsaiHSjw==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:wzMw+7JpYEWvlyGKcGXb5O4WJt7LGzsyCcr2cuJS/eFoHZDK,iv:rfAKGsBCTXWnv/tz46cabDZwLII/4XASZUFIe0Yvl8E=,tag:phm6Ad7YfohFZLvYPgaWkw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1pscs26yljjxv8f4z5x8pdhxv03cllnxs4kjj4k3zlacynd6axg9qa5jcar
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlU01PcnZ1cUludTFCeGVw
        MWs4OFROV09jZmNNZzFzVThrdlZaSXo4TjNvCjlRUGVBUVF1SzFxTnY1UFpWUHRD
        eExWK0FielhLWkVBQ0xvOTR2L0d1YlUKLS0tIDhWWHZiOUFUSkVLTzY3SWFnSGdn
        TzU4RTk0aXV4dlEzekZmZGdWZ21QT0kK9GvGikSjOWxf0IpKy7OsuIzDj59i9c+f
        nYJZkkHAxbM9jQkodKfa4Q7oJ1wJDZU0sQQoCLPi8qgfArxthfDfcg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-08T18:06:25Z"
  mac: ENC[AES256_GCM,data:zR/p/dV5JbteTmDi8CRT6ZtPcb4vJ9cKbV4i/yxYuDZzmeJg+VGidVo2TrFVNz1muVFBPjnQhkSiNlDES/n7KRwWfDMM2/OQ6i7fUM54kl6ikR2rToCwbk4yT/vgcTvDtn6ZmfZm7P9jJlCwgfCWUCHqmsXQQ+AwezMNrCaxYHk=,iv:NHVLxfGGuci9gbZ6jUXgcGgqbsHwYxg/GeKNHMyUmds=,tag:SSWez6pExOP+lzd08h82ew==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
