---
apiVersion: v1
kind: Service
metadata:
  name: intel-gpu-exporter
  labels:
    app.kubernetes.io/name: intel-gpu-exporter
    job: intel-gpu
spec:
  selector:
    app.kubernetes.io/name: intel-gpu-exporter
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
