---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Git:
      - kubesearch:
        - icon: kubernetes-dashboard.png
          href: 'https://kubesearch.dev/'
      - home-ops:
        - icon: github.png
          href: 'https://github.com/tansanrao/nimbus-casa'

  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Administration:
      - Echo Server:
          icon: babybuddy.png
          href: 'https://echo-server.nimbus.casa'
    - Calendar:
      - Agenda:
          widget:
            type: calendar
            view: agenda # optional - possible values monthly, agenda
            maxEvents: 5 # optional - defaults to 10
            integrations: # optional
              - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
                service_group: Media # group name where widget exists
                service_name: Sonarr # service name for that widget
              - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
                service_group: Media # group name where widget exists
                service_name: Radarr # service name for that widget
    - Reading:
      - Miniflux:
          icon: miniflux.png
          href: 'https://miniflux.nimbus.casa'
      - Linkwarden:
          icon: linkwarden.png
          href: 'https://linkwarden.nimbus.casa'
    - Media
      - Jellyfin:
          icon: jellyfin.png
          href: 'https://jellyfin.nimbus.casa'
      - Jellyseerr:
          icon: jellyseerr.png
          href: 'https://jellyseerr.nimbus.casa'
      - Sonarr:
          icon: sonarr.png
          href: 'https://sonarr.nimbus.casa'
  settings.yaml: |
    title: Nimbus Dashboard
    background:
      image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
      opacity: 50
      blur: sm
    color: slate
    headerStyle: clean
    statusStyle: dot
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: false
      hideVisitURL: true
    layout:
      Calendar:
        style: column
        icon: mdi-calendar
        initiallyCollapsed: false
      Administration:
        style: column
        columns: 5
        icon: mdi-network
      Monitoring:
        style: column
        columns: 5
        icon: grafana.png
      Storage:
        style: column
        columns: 5
        icon: synology.png
      Media:
        style: column
        columns: 5
        icon: mdi-download-circle
  widgets.yaml: |
    - search:
        provider: [duckduckgo]
        focus: false
        target: _blank
