---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name homepage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        ## Non Cluster resources
        ## Default
        HOMEPAGE_VAR_PAPERLESS_TOKEN: "{{ .HOMEPAGE_VAR_PAPERLESS_TOKEN }}"
        ## Downloads
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_SABNZBD_TOKEN: "{{ .SABNZBD_API_KEY }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .SONARR_API_KEY }}"
        HOMEPAGE_VAR_JELLYSEERR_TOKEN: "{{ .JELLYSEERR_API_KEY }}"
        HOMEPAGE_VAR_JELLYFIN_TOKEN: "{{ .JELLYFIN_API_KEY }}"
        ## Media
        ## Observability
        ## Security
  dataFrom:
    - extract:
        key: homepage
    - extract:
        key: radarr
    - extract:
        key: sonarr
    - extract:
        key: sabnzbd
    - extract:
        key: jellyseerr
    - extract:
        key: jellyfin
