---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs-pv
  labels:
    app.kubernetes.io/name: immich-nfs
spec:
  capacity:
    storage: 10000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "nfs-immich"
  mountOptions:
    - nfsvers=4.2
    - nconnect=16
    - hard
    - noatime
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nas.kbcb.tansanrao.net/mnt/tank/nimbus/immich
    volumeAttributes:
      server: nas.kbcb.tansanrao.net
      share: /mnt/tank/nimbus/immich
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs-pvc
  labels:
    app.kubernetes.io/name: immich-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10000Gi
  volumeName: immich-nfs-pv
  storageClassName: "nfs-immich"
