---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app meilisearch-karakeep
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: meilisearch-karakeep
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      meilisearch-karakeep:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/getmeili/meilisearch
              tag: v1.43.0@sha256:5d4e1353927785744486fe317d263f442710ab5b27b1983aa1b719dfe2c665b6
            args:
              - /bin/meilisearch
              - --experimental-dumpless-upgrade
            env:
              MEILI_NO_ANALYTICS: "true"
              MEILI_MASTER_KEY:
                valueFrom:
                  secretKeyRef:
                    name: *app
                    key: MEILI_MASTER_KEY
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 4Gi
    service:
      app:
        controller: meilisearch-karakeep
        primary: true
        ports:
          http:
            port: 7700
    persistence:
      data:
        enabled: true
        existingClaim: meilisearch-karakeep
        advancedMounts:
          meilisearch-karakeep:
            app:
              - path: /meili_data
      tmp:
        type: emptyDir
        advancedMounts:
          meilisearch-karakeep:
            app:
              - path: /tmp
