---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediastore-nfs-pv
  labels:
    app.kubernetes.io/name: mediastore-nfs
spec:
  capacity:
    storage: 10000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "nfs-mediastore"
  mountOptions:
    - nfsvers=4.2
    - nconnect=16
    - hard
    - noatime
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: sandcrawler.kbcb.tansanrao.net/tank/mediastore
    volumeAttributes:
      server: sandcrawler.kbcb.tansanrao.net
      share: /tank/mediastore
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediastore-nfs-pvc
  namespace: media
  labels:
    app.kubernetes.io/name: mediastore-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10000Gi
  volumeName: mediastore-nfs-pv
  storageClassName: "nfs-mediastore"
