---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &app linkwarden-secret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *app
    template:
      engineVersion: v2
      data:
        NEXTAUTH_URL: https://links.nimbus.casa/api/v1/auth
        NEXTAUTH_SECRET: "{{ .LINKWARDEN_AUTH_SECRET }}"
        STORAGE_FOLDER: "config"
        HOME: "/data/config"
        NEXT_PUBLIC_OLLAMA_ENDPOINT_URL: "http://ollama-external.ai.svc.cluster.local:11434"
        OLLAMA_MODEL: "llama3.3"
        NEXT_PUBLIC_DISABLE_REGISTRATION: "true"
        NEXT_PUBLIC_AUTHENTIK_ENABLED: "true"
        AUTHENTIK_CUSTOM_NAME: "Nimbus SSO"
        AUTHENTIK_ISSUER: "{{ .LINKWARDEN_AUTH_ISSUER }}"
        AUTHENTIK_CLIENT_ID: "{{ .LINKWARDEN_AUTH_CLIENT_ID }}"
        AUTHENTIK_CLIENT_SECRET: "{{ .LINKWARDEN_AUTH_CLIENT_SECRET }}"
        ARCHIVE_TAKE_COUNT: "1"
        ARCHIVE_SCRIPT_INTERVAL: "30"
  dataFrom:
    - extract:
        key: linkwarden

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &app linkwarden-db-secret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: *app
    template:
      engineVersion: v2
      data:
        DATABASE_URL: &dburi '{{index . "uri" }}'
  dataFrom:
    - extract:
        key: postgres16-pguser-linkwarden
